# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Dev Blog (Coming Soon)
email: Andrew.Mount@gmail.com
description: Just some experiences I've had writing software.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.andymount.com" # the base hostname & protocol for your site
twitter_username: andy_mount
github_username:  armount

# Build settings
markdown: kramdown
